Template.accountsFormTemplate.helpers(AccountsTemplates.atFormHelpers);
Template.accountsFormTemplate.helpers(AccountsTemplates.atTitleHelpers);
Template.accountsFormTemplate.helpers(AccountsTemplates.atPwdFormHelpers);
Template.accountsFormTemplate.events(AccountsTemplates.atPwdFormEvents);
Template.accountsFormTemplate.helpers(AccountsTemplates.atPwdFormBtnHelpers);